[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "lib_sudoku"
version = "1.5"
requires-python = ">=3.8"
description = "A blazing fast sudoku library buit in rust"
readme = "README.md"

[tool.maturin]
include = ["*.pyi", "__init__.py"]

